//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNetWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieSet()
        {
            this.NoteSets = new HashSet<NoteSet>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Duration { get; set; }
        public string Genre { get; set; }
        public string Summary { get; set; }
        public string Image { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual UserSet UserSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteSet> NoteSets { get; set; }
    }
}
